name: Publish
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Publish to GitHub Packages
#        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository --no-configuration-cache
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
      - name: Generate Swift Package
        run: ./gradlew createSwiftPackage
      - name: Commit and push Swift Package
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update Swift Package for version ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push
      - name: Tag Swift Package
        run: |
          git tag -a "spm-${{ github.event.release.tag_name }}" -m "Swift Package Manager release ${{ github.event.release.tag_name }}"
          git push origin "spm-${{ github.event.release.tag_name }}"

