name: Publish
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository --no-configuration-cache
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Generate Swift Package
        run: ./gradlew createSwiftPackage --no-configuration-cache

      - name: Create XCFramework ZIP
        run: |
          cd library/build/XCFrameworks/release
          zip -r networking-${{ github.event.release.tag_name }}.zip networking.xcframework

      - name: Upload XCFramework ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./library/build/XCFrameworks/release/networking-${{ github.event.release.tag_name }}.zip
          asset_name: networking-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

      - name: Send dispatch to library-test
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ferdyrod/library-test/dispatches \
            -d "{\"event_type\":\"update-framework\", \"client_payload\": {\"version\": \"${{ github.event.release.tag_name }}\"}}"
      

